######################################################################
#
# File name : tb_ip_clk_wiz.udo
# Created on: Wed Oct 18 22:05:45 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
