######################################################################
#
# File name : tb_ip_clk_wiz_compile.do
# Created on: Wed Oct 18 22:05:44 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0" \
"../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../ip_clk_wiz.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/ip_clk_wiz.v" \
"../../../../../sim/tb/tb_ip_clk_wiz.v" \


# compile glbl module
D:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

