######################################################################
#
# File name : tb_ip_fifo_wave.do
# Created on: Sat Oct 21 20:53:23 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
