######################################################################
#
# File name : tb_ip_fifo_simulate.do
# Created on: Sat Oct 21 21:01:36 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L fifo_generator_v13_2_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_ip_fifo xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_fifo_wave.do}

view wave
view structure
view signals

do {tb_ip_fifo.udo}

run 1000ns
