######################################################################
#
# File name : tb_ip_2port_ram.udo
# Created on: Fri Oct 20 16:59:55 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
