######################################################################
#
# File name : tb_ip_2port_ram_compile.do
# Created on: Fri Oct 20 16:59:54 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../ip_1port_ram.gen/sources_1/ip/blk_mem_gen_0_1/sim/blk_mem_gen_0.v" \
"../../../../../rtl/ip_1port_ram.v" \
"../../../../../rtl/ram_rw.v" \
"../../../../../sim/tb/tb_ip_1port_ram.v" \


# compile glbl module
D:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

