######################################################################
#
# File name : tb_ip_2port_ram_simulate.do
# Created on: Fri Oct 20 16:59:55 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_ip_2port_ram xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_ip_2port_ram_wave.do}

view wave
view structure
view signals

do {tb_ip_2port_ram.udo}

run 1000ns
