######################################################################
#
# File name : tb_ip_1port_ram_wave.do
# Created on: Thu Oct 19 15:59:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
